### ISSUE TITLE
Not supporting old GPML, easy fix?

### ISSUE THREAD

**Issue by Chris-Evelo** [wikipathways/pvjs#295]
Subject says it all. Can we do an automatic (bot update) for older GPML versions to force they become  fully support and to prevent the PathVisioJS warning from showing up? Martina indicated that I may have stumbled on the error because I looked at an older version of a pathway. According to her the latest version of all pathways should already be fixed. If that is true changing the warning so it says you could try the latest version might be all that is needed.

**Comment by ariutta** [comment]
Yes, the latest version of each pathway is supposed to be GPML2013a, but the older versions have not been updated, although they theoretically could be updated as well.

I tagged this as an "enhancement" request - if a user tries viewing a pre-2013a GPML file, the warning should encourage the user to try viewing the latest version of the pathway.

**Comment by ariutta** [comment]
We have also talked about creating an API endpoint for converting old GPML to the latest schema version. If that existed, we could use it to update older GPML files so pvjs could display them.

**Comment by AlexanderPico** [comment]
Right. There shouldn't be any old GPMLs in the current set of pathways at WikiPathways. If you find one, please report it.

If you mean older revisions, on the other hand, then yes, there are plenty of those. We currently don't apply the GPML upgrade to those, because there is no where to save it, since it's an older revision. But we could think about performing the upgrade locally, just for temporary viewing. I agree that would be an enhancement.

**Comment by khanspers** [comment]
related to #44.
