### ISSUE TITLE
Selections prior to opening editor should stay after opening editor

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#335]
Steps to reproduce:
1. select a datanode (annotations panel will pop up)
2. open editor

Expected behavior: the selected datanode should remain selected (green border) and should fill in the annotations tab, making it active.

Observed behavior: The node remains selected (green border), BUT the annotation tab fields are not filled in and it is not active.

**Comment by AlexanderPico** [comment]
Anders notes: same methods as when toggling between tabs

**Comment by khanspers** [comment]
Also observed: This seems to happen only one time per pathway. Later attempts at the above steps (by Alex) actually does produce the expected behavior.  (this is in Chrome). If pathway page is refreshed it goes back to the behavior seen by Alex.

To try:
1. open any pathway page
2. select a data node
3. open quick edit => annotation fields are blank.
4. close quick edit
5. select a data node
6. open quick edit => the fields are populated based on the selected node.
