### ISSUE TITLE
Labels associated to shapes should not rotate with the shape

### ISSUE THREAD

**Issue by AdamStuart** [wikipathways/pvjs#410]
Steps:   http://www.wikipathways.org/index.php/Pathway:WP2578
Observed:  Text in bottom right corner saying "Golgi Apparatus" is upside down.  Text for ER is vertical.
Expected:  Labels not rotated

**Comment by ariutta** [comment]
Reopened, because the text is no longer rotated, but the Golgi Apparatus is kicked up too high for some reason.

Also, rotated rectangles don't display correctly (JS version on left, Java version on right):
![text-issue](https://user-images.githubusercontent.com/1296771/32353433-b2d4b2bc-bfe2-11e7-9f8d-b81fb5893806.png)
